### ISSUE TITLE
Makefile uses `sed -r` which isn't POSIX standard.

### ISSUE THREAD

**Issue by llamasoft** [strace/strace#216]
The [src/Makefile.am](https://github.com/strace/strace/blob/a0f7df7d3783074b5aac66ea4e55646524164e70/src/Makefile.am) and some build shell scripts use `sed -r` which isn't POSIX standard.  Newer versions of GNU sed recommend using `-E` instead: https://www.gnu.org/software/sed/manual/sed.html#Command_002dLine-Options

> Historically this was a GNU extension, but the -E extension has since been added to the POSIX standard (http://austingroupbugs.net/view.php?id=528), so use -E for portability. GNU sed has accepted -E as an undocumented option for years, and *BSD seds have accepted -E for years as well, but scripts that use -E might not port to other older systems.

`sed -r` also appears in a number test-related scripts, but their appearance there don't interfere with the build process.

**Comment by esyr** [comment]
Note: the support for the option has been (sneakily) added to GNU sed
in v4.1a~8[1] and documented in v4.3~186[2]. Otherwise, I'm not keen
on breaking existing (non-GNU?) environments that do not support this
novelty, unless it fixes some environment(s) where "sed -r" doesn't
work.

[1] https://git.savannah.gnu.org/cgit/sed.git/commit/?id=3a8e165ab024
[2] https://git.savannah.gnu.org/cgit/sed.git/commit/?id=8b65e0790438

**Comment by esyr** [comment]
Note: the support for the option has been (sneakily) added to GNU sed
in v4.1a~8[1] and documented in v4.3~186[2]. Otherwise, I'm not keen
on breaking existing (non-GNU?) environments that do not support this
novelty, unless it fixes some environment(s) where "sed -r" doesn't
work.

[1] https://git.savannah.gnu.org/cgit/sed.git/commit/?id=3a8e165ab024
[2] https://git.savannah.gnu.org/cgit/sed.git/commit/?id=8b65e0790438

-- 
Eugene Syromyatnikov
***@***.***
***@***.***{ru|org}
