### ISSUE TITLE
Unneeded Landlock FD name exception

### ISSUE THREAD

**Issue by l0kod** [strace/strace#222]
Hi,

I noticed that commit https://github.com/strace/strace/commit/d65d4c13fb9f6531399aacb560087e89fc24a282 added an exception for the Landlock ruleset file descriptor name. I think this is not needed because the [original kernel commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=aea0b9f2486da8497f35c7114b764bf55e17c7ea) has been [backported to the latest supported kernel version](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=3d4b396a616d0d67bf95d6823ad1197f6247292e) (Linux 5.15).

Cc @ldv-alt @esyr @brauner

**Comment by esyr** [comment]
On Tue, Aug 30, 2022 at 7:27 PM Mickaël Salaün ***@***.***> wrote:
> I noticed that commit d65d4c1 added an exception for the Landlock ruleset file descriptor name. I think this is not needed because the original kernel commit has been backported to the latest supported kernel version (Linux 5.15).

Since there are kernels released that use the original name, strace
has to account for this ABI breakage (as well as for all others)
virtually forever, as it (as well as its test suite) aims to work on
wide variety of kernels, not only the latest ones.

**Comment by esyr** [comment]
On Tue, Aug 30, 2022 at 7:27 PM Mickaël Salaün ***@***.***> wrote:
> I noticed that commit d65d4c1 added an exception for the Landlock ruleset file descriptor name. I think this is not needed because the original kernel commit has been backported to the latest supported kernel version (Linux 5.15).

Since there are kernels released that use the original name, strace
has to account for this ABI breakage (as well as for all others)
virtually forever, as it (as well as its test suite) aims to work on
wide variety of kernels, not only the latest ones.

-- 
Eugene Syromyatnikov
***@***.***
***@***.***{ru|org}
