### ISSUE TITLE
Get names of files from forked processes

### ISSUE THREAD

**Issue by FrederiqueRetsema** [strace/strace#231]
Hi,

First of all, thank you for making and maintaining this very useful tool. 

I'm trying to get a list of open files from the Apache webserver with strace version 6.0 in an Alpine container:

```
/ # strace -V
strace -- version 6.0
Copyright (c) 1991-2022 The strace developers <https://strace.io>.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Optional features enabled: stack-trace=libdw stack-demangle no-m32-mpers no-mx32-mpers
```

I'm trying the command 

``strace -f -z -e trace=open httpd -D FOREGROUND``

For files that are opened in the main process this works fine: it shows the filename, for example:

``open("/lib/libuuid.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3``

For files in the sub processes, I'm getting hexadecimal values:

``[pid    38] open(0x7ffce6b3a200, O_RDONLY|O_LARGEFILE) = 11``

Is there a flag to get the "real" filenames? Is there another way for me outside strace to know the real file name based on the hexadecimal value? Is this normal behaviour, something that cannot be fixed or is it a bug?

Thank you for your help,

Frederique

**Comment by ldv-alt** [comment]
The hexadecimal value you see is the address in the tracee's memory where the file name is stored.
The reason why you see this value instead of the file name is that strace was denied access to the tracee's memory by the kernel, for example, because the tracee cleared its dumpable flag or changed its credentials, and strace was not privileged enough to get through.

**Comment by FrederiqueRetsema** [comment]
Thank you for your fast response!
