### ISSUE TITLE
No `_newselect` syscall on s390x

### ISSUE THREAD

**Issue by mvo5** [strace/strace#57]
I noticed that strace (4.19) on s390x does not know about the _newselect syscall. When I try to run: `strace -e trace=_newselect` I get `invalid system call '_newselect'`.

I assume there is just no _newselect on s390x (just select) and this is intentional. If so, is there a way for strace to list all syscalls it knows about? If there is no way to do this right now, would you accept a PR to implement this (`strace --list-syscalls` or similar)?

We use strace inside a program and filter out some problematic syscalls with go (golang programs hang strace easily unless certain problematic syscalls are filtered out like select,pselect,gettid). It would be great to have a programmatic way to know if _newselect is available or not.

Thanks,
 Michael

**Comment by esyr** [comment]
There's no ability to list system calls as of now. There was, however, a GSoC 2017 project aimed squarely at that problem [1][2], which is going to be merged at some point. Meanwhile, you can use recently (since strace 4.17) added `-e trace=?syscall` syntax for qualifying syscalls that might not be available.

[1] https://github.com/edosedgar/strace-fork/commits/master
[2] https://summerofcode.withgoogle.com/archive/2017/projects/5658731350065152/

**Comment by mvo5** [comment]
Thanks a lot! I will go with `-e trace=?syscall` for now and look forward to the [1] merge :)
